// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"akmmp241/belajar-golang-restful-api/app"
	"akmmp241/belajar-golang-restful-api/controller"
	"akmmp241/belajar-golang-restful-api/middleware"
	"akmmp241/belajar-golang-restful-api/repository"
	"akmmp241/belajar-golang-restful-api/service"
	"github.com/google/wire"
	"net/http"
)

import (
	_ "github.com/go-sql-driver/mysql"
)

// Injectors from injector.go:

func InitializedServer() *http.Server {
	categoryRepositoryImpl := repository.NewCategoryRepository()
	db := app.NewDB()
	validate := NewValidator()
	categoryService := service.NewCategoryService(categoryRepositoryImpl, db, validate)
	categoryController := controller.NewCategoryController(categoryService)
	router := app.NewRouter(categoryController)
	authMiddleware := middleware.NewAuthMiddleware(router)
	server := NewServer(authMiddleware)
	return server
}

// injector.go:

var categorySet = wire.NewSet(repository.NewCategoryRepository, wire.Bind(new(repository.CategoryRepository), new(*repository.CategoryRepositoryImpl)), service.NewCategoryService, controller.NewCategoryController)
